{% set name = "timefiller" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/timefiller-{{ version }}.tar.gz
  sha256: 3677813d484f8e9bc466647f31bb8e75275ab5f8bfea24bd79f857d2b9193365

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - mapie
    - numba
    - numpy
    - optimask
    - pandas
    - scikit-learn
    - tqdm

test:
  imports:
    - timefiller
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CyrilJl/TimeFiller
  dev_url: https://github.com/CyrilJl/TimeFiller
  doc_url: https://timefiller.readthedocs.io/en/latest/index.html
  summary: A package for imputing missing data in time series
  description: timefiller is a Python package for time series imputation and forecasting. When applied to a set of correlated time series, each series is processed individually, leveraging correlations with the other series as well as its own auto-regressive patterns. The package is designed to be easy to use, even for non-experts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
