{% set name = "timefiller" %}
{% set version = "1.0.5" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/timefiller-{{ version }}.tar.gz
  sha256: 0f0bd61dea2230f9c43160077512d6ac780c4e6708dde4a2e97923094a7fb794

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - mapie
    - numba
    - numpy
    - optimask
    - pandas
    - scikit-learn
    - tqdm

test:
  imports:
    - timefiller
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CyrilJl/TimeFiller
  dev_url: https://github.com/CyrilJl/TimeFiller
  doc_url: https://timefiller.readthedocs.io/en/latest/index.html
  summary: A package for imputing missing data in time series, or forecasting in missing data contexts
  description: timefiller is a Python package for time series imputation and forecasting. When applied to a set of correlated time series, each series is processed individually, leveraging correlations with the other series as well as its own auto-regressive patterns. The package is designed to be easy to use, even for non-experts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
